In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

In [2]:
filePath = '../../data/evaluation/recentGames/2024.csv'
df = pd.read_csv(filePath)

In [3]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,BFH,BFD,BFA,PSH,PSD,PSA,WHH,WHD,WHA,1XBH,1XBD,1XBA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,BFEH,BFED,BFEA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,BFE>2.5,BFE<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,BFEAHH,BFEAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,BFCH,BFCD,BFCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,1XBCH,1XBCD,1XBCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,BFECH,BFECD,BFECA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,BFEC>2.5,BFEC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,D,R Jones,14,10,5,2,12,10,7,8,2,3,0,0,1.60,4.20,5.25,1.60,4.4,5.25,1.60,4.33,5.00,1.63,4.38,5.30,1.65,4.2,5.00,1.68,4.32,5.03,1.68,4.50,5.50,1.62,4.36,5.15,1.66,4.50,5.60,1.53,2.50,1.56,2.56,1.57,2.60,1.53,2.52,1.59,2.64,-1.00,2.05,1.88,2.07,1.86,2.07,1.89,2.03,1.85,2.10,1.88,1.67,4.10,5.00,1.65,4.20,4.80,1.62,4.0,5.00,1.65,4.23,5.28,1.60,4.2,5.50,1.66,4.15,5.33,1.70,4.33,5.50,1.66,4.20,5.02,1.72,4.20,5.40,1.62,2.30,1.63,2.38,1.66,2.45,1.61,2.37,1.68,2.46,-0.75,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,7,18,2,5,9,18,2,10,3,1,0,0,8.50,5.50,1.33,7.50,5.5,1.36,8.50,5.50,1.33,8.18,5.84,1.34,8.50,5.5,1.33,8.60,5.85,1.35,9.00,6.10,1.37,8.28,5.76,1.34,9.40,6.20,1.36,1.40,3.00,1.41,3.00,1.43,3.07,1.41,2.94,1.45,3.15,1.50,2.02,1.91,1.99,1.92,2.02,1.95,1.97,1.90,2.04,1.93,8.00,5.75,1.33,8.00,5.75,1.34,7.50,5.5,1.33,8.14,6.09,1.34,8.00,5.5,1.35,8.57,5.85,1.34,8.57,6.25,1.39,7.87,5.81,1.35,8.60,6.20,1.37,1.36,3.20,1.37,3.30,1.40,3.38,1.37,3.18,1.40,3.40,1.50,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,18,9,6,3,17,14,8,2,2,2,0,0,1.18,7.50,13.00,1.20,7.5,13.50,1.15,8.00,16.00,1.16,8.56,16.22,1.18,7.0,17.00,1.20,7.65,16.00,1.20,9.10,18.00,1.18,7.86,15.87,1.19,9.00,18.00,1.44,2.75,1.46,2.79,1.50,2.82,1.46,2.70,1.53,2.84,-2.00,1.93,2.00,1.88,2.00,1.97,2.00,1.90,1.96,1.94,2.00,1.14,8.50,15.00,1.16,8.50,18.00,1.13,8.5,17.00,1.15,9.05,18.76,1.15,8.0,19.00,1.16,9.39,16.60,1.17,9.40,21.00,1.15,8.62,18.11,1.17,9.40,21.00,1.40,3.00,1.41,2.98,1.45,3.00,1.42,2.93,1.44,3.20,-2.25,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,A,S Hooper,9,10,1,5,8,8,1,5,1,1,1,0,2.63,3.30,2.63,2.65,3.4,2.60,2.70,3.40,2.63,2.73,3.36,2.71,2.60,3.5,2.70,2.68,3.66,2.63,2.76,3.66,2.78,2.67,3.41,2.68,2.78,3.50,2.78,1.80,2.00,1.83,2.05,1.85,2.08,1.81,2.04,1.88,2.08,0.00,1.96,1.97,1.96,1.94,1.97,1.97,1.94,1.94,1.99,1.99,3.10,3.40,2.30,3.00,3.40,2.37,3.00,3.3,2.30,3.15,3.41,2.40,3.10,3.3,2.40,3.16,3.47,2.34,3.16,3.50,2.45,3.06,3.40,2.38,3.15,3.55,2.46,1.93,1.97,1.93,1.97,1.95,2.00,1.89,1.96,1.94,2.04,0.25,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,3,19,1,4,15,16,3,12,2,4,1,0,1.36,5.25,8.00,1.35,5.5,7.75,1.33,5.50,8.50,1.35,5.70,8.25,1.35,5.5,8.00,1.37,5.74,8.10,1.37,5.90,8.60,1.35,5.62,8.10,1.37,6.00,9.20,1.40,3.00,1.40,3.09,1.42,3.12,1.40,3.01,1.43,3.15,-1.50,1.98,1.95,1.94,1.96,1.99,1.98,1.93,1.93,1.94,2.01,1.40,5.00,7.00,1.39,5.25,7.25,1.36,5.0,7.50,1.42,5.30,7.26,1.40,5.0,7.50,1.39,5.34,7.90,1.44,5.75,8.00,1.39,5.27,7.33,1.43,5.50,8.20,1.44,2.75,1.46,2.85,1.46,3.05,1.43,2.84,1.49,2.98,-1.25,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,D,T Harrington,17,14,6,6,12,9,12,3,1,4,0,0,1.33,5.50,8.50,NaN,NaN,NaN,1.30,5.50,9.00,1.33,5.85,8.55,NaN,NaN,NaN,1.36,5.70,8.85,1.36,5.85,9.50,1.32,5.60,8.77,1.35,6.20,9.60,1.53,2.50,1.52,2.62,1.53,2.65,1.50,2.55,1.58,2.62,-1.50,1.93,1.93,1.95,1.95,1.95,1.96,1.90,1.93,1.85,2.05,1.29,6.00,9.50,NaN,NaN,NaN,1.25,6.0,12.00,1.28,6.19,10.36,NaN,NaN,NaN,1.30,6.11,10.20,1.30,6.60,12.50,1.27,6.18,10.88,1.27,7.00,13.00,1.44,2.75,1.47,2.75,1.50,2.81,1.47,2.71,1.50,2.94,-1.75,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,D,A Taylor,10,6,2,2,10,11,7,4,2,2,0,0,3.00,3.75,2.20,NaN,NaN,NaN,3.20,3.60,2.15,3.15,3.76,2.22,NaN,NaN,NaN,3.19,3.73,2.25,3.20,3.85,2.25,3.09,3.72,2.20,3.30,3.90,2.24,1.67,2.20,1.68,2.25,1.72,2.26,1.67,2.21,1.77,2.28,0.25,1.93,1.93,1.96,1.94,1.96,1.94,1.92,1.87,2.03,1.96,3.40,3.75,2.00,NaN,NaN,NaN,3.40,3.6,2.05,3.50,3.87,2.07,NaN,NaN,NaN,3.50,3.86,2.06,3.55,3.90,2.11,3.44,3.78,2.06,3.55,3.90,2.14,1.67,2.20,1.70,2.24,1.71,2.28,1.68,2.21,1.76,2.28,0.50,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,A,D Bond,7,23,2,8,7,8,5,8,0,0,0,0,8.50,6.00,1.30,NaN,NaN,NaN,11.00,5.50,1.25,9.46,5.85,1.30,NaN,NaN,NaN,10.40,6.11,1.31,11.00,6.11,1.31,9.45,5.83,1.29,11.50,6.40,1.31,1.50,2.63,1.50,2.67,1.50,2.80,1.47,2.64,1.52,2.78,1.50,2.03,1.83,2.06,1.83,2.06,1.86,2.02,1.82,1.89,1.31,12.00,6.00,1.25,NaN,NaN,NaN,12.00,6.0,1.22,11.73,6.54,1.25,NaN,NaN,NaN,12.20,6.11,1.28,12.20,6.80,1.28,11.73,6.40,1.25,13.00,6.80,1.28,1.40,3.00,1.41,2.99,1.41,3.05,1.40,2.97,1.45,3.15,1.75,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,H,R Jones,4,23,2,8,13,8,2,11,3,1,0,0,4.20,4.33,1.70,NaN,NaN,NaN,4.20,4.40,1.70,4.33,4.52,1.71,NaN,NaN,NaN,4.38,4.54,1.73,4.38,4.55,1.73,4.23,4.43,1.71,4.40,4.70,1.75,1.33,3.40,1.34,3.38,1.34,3.55,1.32,3.34,1.35,3.65,0.75,2.00,1.85,2.02,1.88,2.02,1.92,1.97,1.85,1.64,1.75,3.70,4.00,1.85,NaN,NaN,NaN,3.75,3.9,1.87,3.83,4.06,1.92,NaN,NaN,NaN,3.63,4.12,1.95,3.90,4.15,1.95,3.71,4.02,1.91,3.95,4.20,1.93,1.50,2.63,1.49,2.72,1.51,2.80,1.47,2.69,1.51,2.92,0.50,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,A,C Pawson,18,13,6,7,7,9,8,3,2,1,0,0,2.70,3.70,2.45,NaN,NaN,NaN,2.75,3.60,2.45,2.74,3.83,2.45,NaN,NaN,NaN,2.77,3.85,2.47,2.77,3.85,2.48,2.71,3.76,2.43,2.86,3.85,2.54,1.53,2.50,1.53,2.56,1.53,2.63,1.50,2.55,1.55,2.74,0.00,2.03,1.83,2.07,1.85,2.07,1.85,2.04,1.82,2.11,1.88,2.90,3.70,2.25,NaN,NaN,NaN,2.90,3.6,2.30,3.00,3.82,2.31,NaN,NaN,NaN,2.98,3.80,2.31,3.00,3.82,2.45,2.91,3.74,2.32,3.05,3.80,2.42,1.50,2.63,1.52,2.63,1.52,2.63,1.50,2.60,1.54,2.78,0.25,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [4]:
columns_to_keep = [
    'Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
    'HTHG', 'HTAG', 'HTR', 'Attendance', 'Referee', 'HS', 'AS', 'HST', 'AST',
    'HHW', 'AHW', 'HC', 'AC', 'HF', 'AF', 'HFKC', 'AFKC', 'HO', 'AO', 'HY', 'AY',
    'HR', 'AR', '1XBH', '1XBD', '1XBA', 'B365H', 'B365D', 'B365A', 'B365>2.5', 'B365<2.5', 'B365AHH', 'B365AHA', 'B365AH',
    'BFH', 'BFD', 'BFA', 'BFEH', 'BFED', 'BFEA', 'BFDH', 'BFDD', 'BFDA',
    'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'VCH', 'VCD', 'VCA',
    'BSH', 'BSD', 'BSA', 'BWH', 'BWD', 'BWA', 'CLH', 'CLD', 'CLA',
    'GBH', 'GBD', 'GBA', 'GB>2.5', 'GB<2.5', 'GBAHH', 'GBAHA', 'GBAH',
    'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'LBAHH', 'LBAHA', 'LBAH',
    'PSH', 'PH', 'PSD', 'PD', 'PSA', 'PA', 'P>2.5', 'P<2.5', 'PAHH', 'PAHA',
    'SOH', 'SOD', 'SOA', 'SBH', 'SBD', 'SBA', 'SJH', 'SJD', 'SJA',
    'SYH', 'SYD', 'SYA', 'WHH', 'WHD', 'WHA',
    'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA',
    'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5',
    'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
    'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA',
    'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5',
    'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'AHh'
]

df = df[[col for col in columns_to_keep if col in df.columns]]

In [5]:
drop_cols = ['Time', 'Attendance', 'HHW', 'AHW', 'HO', 'AO', 'Div']
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

In [6]:
def date_format_type(date_str):
    if not isinstance(date_str, str):
        return "not_a_string"
    patterns = {
        "%d/%m/%y": r"^\d{2}/\d{2}/\d{2}$",
        "%d/%m/%Y": r"^\d{2}/\d{2}/\d{4}$",
        "%Y-%m-%d": r"^\d{4}-\d{2}-\d{2}$",
        "%m-%d-%Y": r"^\d{2}-\d{2}-\d{4}$",
        "%Y/%m/%d": r"^\d{4}/\d{2}/\d{2}$",
    }
    for fmt, pat in patterns.items():
        if re.match(pat, date_str):
            return fmt
    return "unknown"

In [7]:
df['DateFormat'] = df['Date'].apply(date_format_type)
def parse_dates(row):
    date_str = row['Date']
    if isinstance(date_str, str):
        try:
            return pd.to_datetime(date_str, format='%d/%m/%y')
        except ValueError:
            try:
                return pd.to_datetime(date_str, format='%d/%m/%Y')
            except ValueError:
                return pd.NaT
    else:
        return pd.NaT

df['Date'] = df.apply(parse_dates, axis=1)
df = df.drop(columns=['DateFormat'], errors='ignore')
df = df[df['Date'] >= pd.Timestamp('2000-08-18')]
df = df.reset_index(drop=True)

def get_season(date):
    if pd.isnull(date):
        return np.nan
    year = date.year
    month = date.month
    if month >= 8: 
        return f"{year}-{str(year+1)[-2:]}"
    else:
        return f"{year-1}-{str(year)[-2:]}"
df['Season'] = df['Date'].apply(get_season)
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['DayOfWeek'] = df['Date'].dt.dayofweek

In [8]:
df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,14,10,5,2,7,8,12,10,2,3,0,0,1.68,4.32,5.03,1.60,4.20,5.25,1.53,2.50,2.05,1.88,1.60,4.33,5.00,1.66,4.50,5.60,1.60,4.4,5.25,1.63,4.38,5.30,1.56,2.56,2.07,1.86,1.65,4.2,5.00,1.68,4.50,5.50,1.62,4.36,5.15,1.57,2.60,1.53,2.52,2.07,1.89,2.03,1.85,-1.00,2024-25,2024,8,4
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,7,18,2,5,2,10,9,18,3,1,0,0,8.60,5.85,1.35,8.50,5.50,1.33,1.40,3.00,2.02,1.91,8.50,5.50,1.33,9.40,6.20,1.36,7.50,5.5,1.36,8.18,5.84,1.34,1.41,3.00,1.99,1.92,8.50,5.5,1.33,9.00,6.10,1.37,8.28,5.76,1.34,1.43,3.07,1.41,2.94,2.02,1.95,1.97,1.90,1.50,2024-25,2024,8,5
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,18,9,6,3,8,2,17,14,2,2,0,0,1.20,7.65,16.00,1.18,7.50,13.00,1.44,2.75,1.93,2.00,1.15,8.00,16.00,1.19,9.00,18.00,1.20,7.5,13.50,1.16,8.56,16.22,1.46,2.79,1.88,2.00,1.18,7.0,17.00,1.20,9.10,18.00,1.18,7.86,15.87,1.50,2.82,1.46,2.70,1.97,2.00,1.90,1.96,-2.00,2024-25,2024,8,5
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,9,10,1,5,1,5,8,8,1,1,1,0,2.68,3.66,2.63,2.63,3.30,2.63,1.80,2.00,1.96,1.97,2.70,3.40,2.63,2.78,3.50,2.78,2.65,3.4,2.60,2.73,3.36,2.71,1.83,2.05,1.96,1.94,2.60,3.5,2.70,2.76,3.66,2.78,2.67,3.41,2.68,1.85,2.08,1.81,2.04,1.97,1.97,1.94,1.94,0.00,2024-25,2024,8,5
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,3,19,1,4,3,12,15,16,2,4,1,0,1.37,5.74,8.10,1.36,5.25,8.00,1.40,3.00,1.98,1.95,1.33,5.50,8.50,1.37,6.00,9.20,1.35,5.5,7.75,1.35,5.70,8.25,1.40,3.09,1.94,1.96,1.35,5.5,8.00,1.37,5.90,8.60,1.35,5.62,8.10,1.42,3.12,1.40,3.01,1.99,1.98,1.93,1.93,-1.50,2024-25,2024,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2025-05-25,Newcastle,Everton,0,1,A,0,0,D,T Harrington,17,14,6,6,12,3,12,9,1,4,0,0,1.36,5.70,8.85,1.33,5.50,8.50,1.53,2.50,1.93,1.93,1.30,5.50,9.00,1.35,6.20,9.60,NaN,NaN,NaN,1.33,5.85,8.55,1.52,2.62,1.95,1.95,NaN,NaN,NaN,1.36,5.85,9.50,1.32,5.60,8.77,1.53,2.65,1.50,2.55,1.95,1.96,1.90,1.93,-1.50,2024-25,2025,5,6
376,2025-05-25,Nott'm Forest,Chelsea,0,1,A,0,0,D,A Taylor,10,6,2,2,7,4,10,11,2,2,0,0,3.19,3.73,2.25,3.00,3.75,2.20,1.67,2.20,1.93,1.93,3.20,3.60,2.15,3.30,3.90,2.24,NaN,NaN,NaN,3.15,3.76,2.22,1.68,2.25,1.96,1.94,NaN,NaN,NaN,3.20,3.85,2.25,3.09,3.72,2.20,1.72,2.26,1.67,2.21,1.96,1.94,1.92,1.87,0.25,2024-25,2025,5,6
377,2025-05-25,Southampton,Arsenal,1,2,A,0,1,A,D Bond,7,23,2,8,5,8,7,8,0,0,0,0,10.40,6.11,1.31,8.50,6.00,1.30,1.50,2.63,2.03,1.83,11.00,5.50,1.25,11.50,6.40,1.31,NaN,NaN,NaN,9.46,5.85,1.30,1.50,2.67,2.06,1.83,NaN,NaN,NaN,11.00,6.11,1.31,9.45,5.83,1.29,1.50,2.80,1.47,2.64,2.06,1.86,2.02,1.82,1.50,2024-25,2025,5,6
378,2025-05-25,Tottenham,Brighton,1,4,A,1,0,H,R Jones,4,23,2,8,2,11,13,8,3,1,0,0,4.38,4.54,1.73,4.20,4.33,1.70,1.33,3.40,2.00,1.85,4.20,4.40,1.70,4.40,4.70,1.75,NaN,NaN,NaN,4.33,4.52,1.71,1.34,3.38,2.02,1.88,NaN,NaN,NaN,4.38,4.55,1.73,4.23,4.43,1.71,1.34,3.55,1.32,3.34,2.02,1.92,1.97,1.85,0.75,2024-25,2025,5,6
379,2025-05-25,Wolves,Brentford,1,1,D,0,1,A,C Pawson,18,13,6,7,8,3,7,9,2,1,0,0,2.77,3.85,2.47,2.70,3.70,2.45,1.53,2.50,2.03,1.83,2.75,3.60,2.45,2.86,3.85,2.54,NaN,NaN,NaN,2.74,3.83,2.45,1.53,2.56,2.07,1.85,NaN,NaN,NaN,2.77,3.85,2.48,2.71,3.76,2.43,1.53,2.63,1.50,2.55,2.07,1.85,2.04,1.82,0.00,2024-25,2025,5,6

In [9]:
odds_cols = [
    'B365H', 'B365D', 'B365A', 'B365>2.5', 'B365<2.5', 'B365AHH', 'B365AHA', 'B365AH',
    'IWH', 'IWD', 'IWA',
    'WHH', 'WHD', 'WHA',
    'PSH', 'PSD', 'PSA', 'PH', 'PD', 'PA', 'P>2.5', 'P<2.5', 'PAHH', 'PAHA',
    'LBH', 'LBD', 'LBA', 'LBAHH', 'LBAHA', 'LBAH',
    'GBH', 'GBD', 'GBA', 'GB>2.5', 'GB<2.5', 'GBAHH', 'GBAHA', 'GBAH',
    'BVH', 'BVD', 'BVA', 'VCH', 'VCD', 'VCA',
    '1XBH', '1XBD', '1XBA',
    'BWH', 'BWD', 'BWA',
    'SOH', 'SOD', 'SOA',
    'SBH', 'SBD', 'SBA',
    'CLH', 'CLD', 'CLA',
    'BMGMH', 'BMGMD', 'BMGMA',
    'BFDH', 'BFDD', 'BFDA',
    'BFH', 'BFD', 'BFA', 'BFEH', 'BFED', 'BFEA',
    'SYH', 'SYD', 'SYA',
    'SJH', 'SJD', 'SJA',
    'BSH', 'BSD', 'BSA',
    'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5',
    'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
    'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA',
    'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5',
    'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'AHh'
]

score_cols = [
    'FTHG', 'FTAG', 'HTHG', 'HTAG', 'HS', 'AS', 'HST', 'AST',  
    'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR'
]

In [10]:
for col in odds_cols + score_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

df = df.drop_duplicates()

In [11]:
df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,14,10,5,2,7,8,12,10,2,3,0,0,1.68,4.32,5.03,1.60,4.20,5.25,1.53,2.50,2.05,1.88,1.60,4.33,5.00,1.66,4.50,5.60,1.60,4.4,5.25,1.63,4.38,5.30,1.56,2.56,2.07,1.86,1.65,4.2,5.00,1.68,4.50,5.50,1.62,4.36,5.15,1.57,2.60,1.53,2.52,2.07,1.89,2.03,1.85,-1.00,2024-25,2024,8,4
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,7,18,2,5,2,10,9,18,3,1,0,0,8.60,5.85,1.35,8.50,5.50,1.33,1.40,3.00,2.02,1.91,8.50,5.50,1.33,9.40,6.20,1.36,7.50,5.5,1.36,8.18,5.84,1.34,1.41,3.00,1.99,1.92,8.50,5.5,1.33,9.00,6.10,1.37,8.28,5.76,1.34,1.43,3.07,1.41,2.94,2.02,1.95,1.97,1.90,1.50,2024-25,2024,8,5
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,18,9,6,3,8,2,17,14,2,2,0,0,1.20,7.65,16.00,1.18,7.50,13.00,1.44,2.75,1.93,2.00,1.15,8.00,16.00,1.19,9.00,18.00,1.20,7.5,13.50,1.16,8.56,16.22,1.46,2.79,1.88,2.00,1.18,7.0,17.00,1.20,9.10,18.00,1.18,7.86,15.87,1.50,2.82,1.46,2.70,1.97,2.00,1.90,1.96,-2.00,2024-25,2024,8,5
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,9,10,1,5,1,5,8,8,1,1,1,0,2.68,3.66,2.63,2.63,3.30,2.63,1.80,2.00,1.96,1.97,2.70,3.40,2.63,2.78,3.50,2.78,2.65,3.4,2.60,2.73,3.36,2.71,1.83,2.05,1.96,1.94,2.60,3.5,2.70,2.76,3.66,2.78,2.67,3.41,2.68,1.85,2.08,1.81,2.04,1.97,1.97,1.94,1.94,0.00,2024-25,2024,8,5
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,3,19,1,4,3,12,15,16,2,4,1,0,1.37,5.74,8.10,1.36,5.25,8.00,1.40,3.00,1.98,1.95,1.33,5.50,8.50,1.37,6.00,9.20,1.35,5.5,7.75,1.35,5.70,8.25,1.40,3.09,1.94,1.96,1.35,5.5,8.00,1.37,5.90,8.60,1.35,5.62,8.10,1.42,3.12,1.40,3.01,1.99,1.98,1.93,1.93,-1.50,2024-25,2024,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2025-05-25,Newcastle,Everton,0,1,A,0,0,D,T Harrington,17,14,6,6,12,3,12,9,1,4,0,0,1.36,5.70,8.85,1.33,5.50,8.50,1.53,2.50,1.93,1.93,1.30,5.50,9.00,1.35,6.20,9.60,NaN,NaN,NaN,1.33,5.85,8.55,1.52,2.62,1.95,1.95,NaN,NaN,NaN,1.36,5.85,9.50,1.32,5.60,8.77,1.53,2.65,1.50,2.55,1.95,1.96,1.90,1.93,-1.50,2024-25,2025,5,6
376,2025-05-25,Nott'm Forest,Chelsea,0,1,A,0,0,D,A Taylor,10,6,2,2,7,4,10,11,2,2,0,0,3.19,3.73,2.25,3.00,3.75,2.20,1.67,2.20,1.93,1.93,3.20,3.60,2.15,3.30,3.90,2.24,NaN,NaN,NaN,3.15,3.76,2.22,1.68,2.25,1.96,1.94,NaN,NaN,NaN,3.20,3.85,2.25,3.09,3.72,2.20,1.72,2.26,1.67,2.21,1.96,1.94,1.92,1.87,0.25,2024-25,2025,5,6
377,2025-05-25,Southampton,Arsenal,1,2,A,0,1,A,D Bond,7,23,2,8,5,8,7,8,0,0,0,0,10.40,6.11,1.31,8.50,6.00,1.30,1.50,2.63,2.03,1.83,11.00,5.50,1.25,11.50,6.40,1.31,NaN,NaN,NaN,9.46,5.85,1.30,1.50,2.67,2.06,1.83,NaN,NaN,NaN,11.00,6.11,1.31,9.45,5.83,1.29,1.50,2.80,1.47,2.64,2.06,1.86,2.02,1.82,1.50,2024-25,2025,5,6
378,2025-05-25,Tottenham,Brighton,1,4,A,1,0,H,R Jones,4,23,2,8,2,11,13,8,3,1,0,0,4.38,4.54,1.73,4.20,4.33,1.70,1.33,3.40,2.00,1.85,4.20,4.40,1.70,4.40,4.70,1.75,NaN,NaN,NaN,4.33,4.52,1.71,1.34,3.38,2.02,1.88,NaN,NaN,NaN,4.38,4.55,1.73,4.23,4.43,1.71,1.34,3.55,1.32,3.34,2.02,1.92,1.97,1.85,0.75,2024-25,2025,5,6
379,2025-05-25,Wolves,Brentford,1,1,D,0,1,A,C Pawson,18,13,6,7,8,3,7,9,2,1,0,0,2.77,3.85,2.47,2.70,3.70,2.45,1.53,2.50,2.03,1.83,2.75,3.60,2.45,2.86,3.85,2.54,NaN,NaN,NaN,2.74,3.83,2.45,1.53,2.56,2.07,1.85,NaN,NaN,NaN,2.77,3.85,2.48,2.71,3.76,2.43,1.53,2.63,1.50,2.55,2.07,1.85,2.04,1.82,0.00,2024-25,2025,5,6

In [12]:
essential_odds = ['B365H', 'B365D', 'B365A', 'WHH', 'WHD', 'WHA', 'IWH', 'IWD', 'IWA']

core_odds = [
    'B365H', 'B365D', 'B365A', 'B365>2.5', 'B365<2.5', 'B365AHH', 'B365AHA', 'B365AH',
    'IWH', 'IWD', 'IWA',
    'WHH', 'WHD', 'WHA',
    'PSH', 'PSD', 'PSA', 'PH', 'PD', 'PA', 'P>2.5', 'P<2.5', 'PAHH', 'PAHA',
    'LBH', 'LBD', 'LBA', 'LBAHH', 'LBAHA', 'LBAH',
    'GBH', 'GBD', 'GBA', 'GB>2.5', 'GB<2.5', 'GBAHH', 'GBAHA', 'GBAH',
    'BVH', 'BVD', 'BVA', 'VCH', 'VCD', 'VCA',
    '1XBH', '1XBD', '1XBA',
    'BWH', 'BWD', 'BWA',
    'SOH', 'SOD', 'SOA',
    'SBH', 'SBD', 'SBA',
    'CLH', 'CLD', 'CLA',
    'BMGMH', 'BMGMD', 'BMGMA',
    'BFDH', 'BFDD', 'BFDA',
    'BFH', 'BFD', 'BFA', 'BFEH', 'BFED', 'BFEA',
    'SYH', 'SYD', 'SYA',
    'SJH', 'SJD', 'SJA',
    'BSH', 'BSD', 'BSA',
    'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5',
    'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA',
    'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA',
    'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5',
    'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'AHh'
]

def clean_odds_dataframe(df, essential_odds, core_odds, fill_method='mean'):
    essentials = [col for col in essential_odds if col in df.columns]
    df = df.dropna(subset=essentials).reset_index(drop=True)
   
    for col in core_odds:
        if col in df.columns:
            if fill_method == 'mean':
                fill_value = df[col].mean()
            elif fill_method == 'median':
                fill_value = df[col].median()
            elif fill_method == 'zero':
                fill_value = 0
            elif fill_method == 'negone':
                fill_value = -1
            else:
                fill_value = None
            if fill_value is not None:
                df[col] = df[col].fillna(fill_value)
    return df

df = clean_odds_dataframe(df, essential_odds, core_odds, fill_method='mean')
df = df.reset_index(drop=True)

In [13]:
df

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek
0,2024-08-16,Man United,Fulham,1,0,H,0,0,D,R Jones,14,10,5,2,7,8,12,10,2,3,0,0,1.68,4.32,5.03,1.60,4.20,5.25,1.53,2.50,2.05,1.88,1.60,4.33,5.00,1.66,4.50,5.60,1.600000,4.400000,5.250000,1.63,4.38,5.30,1.56,2.56,2.07,1.86,1.65,4.20,5.00,1.68,4.50,5.50,1.62,4.36,5.15,1.57,2.60,1.53,2.52,2.07,1.89,2.03,1.85,-1.00,2024-25,2024,8,4
1,2024-08-17,Ipswich,Liverpool,0,2,A,0,0,D,T Robinson,7,18,2,5,2,10,9,18,3,1,0,0,8.60,5.85,1.35,8.50,5.50,1.33,1.40,3.00,2.02,1.91,8.50,5.50,1.33,9.40,6.20,1.36,7.500000,5.500000,1.360000,8.18,5.84,1.34,1.41,3.00,1.99,1.92,8.50,5.50,1.33,9.00,6.10,1.37,8.28,5.76,1.34,1.43,3.07,1.41,2.94,2.02,1.95,1.97,1.90,1.50,2024-25,2024,8,5
2,2024-08-17,Arsenal,Wolves,2,0,H,1,0,H,J Gillett,18,9,6,3,8,2,17,14,2,2,0,0,1.20,7.65,16.00,1.18,7.50,13.00,1.44,2.75,1.93,2.00,1.15,8.00,16.00,1.19,9.00,18.00,1.200000,7.500000,13.500000,1.16,8.56,16.22,1.46,2.79,1.88,2.00,1.18,7.00,17.00,1.20,9.10,18.00,1.18,7.86,15.87,1.50,2.82,1.46,2.70,1.97,2.00,1.90,1.96,-2.00,2024-25,2024,8,5
3,2024-08-17,Everton,Brighton,0,3,A,0,1,A,S Hooper,9,10,1,5,1,5,8,8,1,1,1,0,2.68,3.66,2.63,2.63,3.30,2.63,1.80,2.00,1.96,1.97,2.70,3.40,2.63,2.78,3.50,2.78,2.650000,3.400000,2.600000,2.73,3.36,2.71,1.83,2.05,1.96,1.94,2.60,3.50,2.70,2.76,3.66,2.78,2.67,3.41,2.68,1.85,2.08,1.81,2.04,1.97,1.97,1.94,1.94,0.00,2024-25,2024,8,5
4,2024-08-17,Newcastle,Southampton,1,0,H,1,0,H,C Pawson,3,19,1,4,3,12,15,16,2,4,1,0,1.37,5.74,8.10,1.36,5.25,8.00,1.40,3.00,1.98,1.95,1.33,5.50,8.50,1.37,6.00,9.20,1.350000,5.500000,7.750000,1.35,5.70,8.25,1.40,3.09,1.94,1.96,1.35,5.50,8.00,1.37,5.90,8.60,1.35,5.62,8.10,1.42,3.12,1.40,3.01,1.99,1.98,1.93,1.93,-1.50,2024-25,2024,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,2025-03-15,Southampton,Wolves,1,2,A,0,1,A,R Jones,10,5,3,3,5,1,12,13,0,0,0,0,3.71,3.55,2.11,3.70,3.40,2.00,1.84,2.06,1.83,2.07,3.80,3.50,2.00,3.95,3.65,2.10,2.737992,4.417531,4.333264,3.67,3.56,2.08,1.82,2.07,1.83,2.09,3.70,3.40,2.05,3.85,3.65,2.11,3.63,3.51,2.06,1.86,2.10,1.81,2.03,1.85,2.09,1.80,2.05,0.50,2024-25,2025,3,5
285,2025-03-15,Bournemouth,Brentford,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5
286,2025-03-16,Arsenal,Chelsea,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6
287,2025-03-16,Fulham,Tottenham,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6
288,2025-03-16,Leicester,Man United,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6

In [14]:
df['TotalGoals'] = df['FTHG'] + df['FTAG']
df['GoalsOver2_5'] = (df['TotalGoals'] > 2.5).astype(int)
df['BTTS'] = ((df['FTHG'] > 0) & (df['FTAG'] > 0)).astype(int)
df['Home_2plus'] = (df['FTHG'] >= 2).astype(int)
df['Away_2plus'] = (df['FTAG'] >= 2).astype(int)

In [15]:
df = df.sort_values('Date')
df['HomeTeam_mean_FTHG'] = (
    df.groupby('HomeTeam')['FTHG'].transform(lambda x: x.shift(1).expanding().mean())
)
df['AwayTeam_mean_FTAG'] = (
    df.groupby('AwayTeam')['FTAG'].transform(lambda x: x.shift(1).expanding().mean())
)

In [16]:
df['HomeTeam_str'] = df['HomeTeam']
df['AwayTeam_str'] = df['AwayTeam']
df = pd.get_dummies(df, columns=['HomeTeam', 'AwayTeam'])
df = df.rename(columns={'HomeTeam_str': 'HomeTeam', 'AwayTeam_str': 'AwayTeam'})

In [17]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves
0,2024-08-16,1,0,H,0,0,D,R Jones,14,10,5,2,7,8,12,10,2,3,0,0,1.68,4.32,5.03,1.60,4.20,5.25,1.53,2.50,2.05,1.88,1.60,4.33,5.00,1.66,4.50,5.60,1.600000,4.400000,5.250000,1.63,4.38,5.30,1.56,2.56,2.07,1.86,1.65,4.20,5.00,1.68,4.50,5.50,1.62,4.36,5.15,1.57,2.60,1.53,2.52,2.07,1.89,2.03,1.85,-1.00,2024-25,2024,8,4,1,0,0,0,0,NaN,NaN,Man United,Fulham,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,2024-08-17,0,2,A,0,0,D,T Robinson,7,18,2,5,2,10,9,18,3,1,0,0,8.60,5.85,1.35,8.50,5.50,1.33,1.40,3.00,2.02,1.91,8.50,5.50,1.33,9.40,6.20,1.36,7.500000,5.500000,1.360000,8.18,5.84,1.34,1.41,3.00,1.99,1.92,8.50,5.50,1.33,9.00,6.10,1.37,8.28,5.76,1.34,1.43,3.07,1.41,2.94,2.02,1.95,1.97,1.90,1.50,2024-25,2024,8,5,2,0,0,0,1,NaN,NaN,Ipswich,Liverpool,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,2024-08-17,2,0,H,1,0,H,J Gillett,18,9,6,3,8,2,17,14,2,2,0,0,1.20,7.65,16.00,1.18,7.50,13.00,1.44,2.75,1.93,2.00,1.15,8.00,16.00,1.19,9.00,18.00,1.200000,7.500000,13.500000,1.16,8.56,16.22,1.46,2.79,1.88,2.00,1.18,7.00,17.00,1.20,9.10,18.00,1.18,7.86,15.87,1.50,2.82,1.46,2.70,1.97,2.00,1.90,1.96,-2.00,2024-25,2024,8,5,2,0,0,1,0,NaN,NaN,Arsenal,Wolves,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,2024-08-17,0,3,A,0,1,A,S Hooper,9,10,1,5,1,5,8,8,1,1,1,0,2.68,3.66,2.63,2.63,3.30,2.63,1.80,2.00,1.96,1.97,2.70,3.40,2.63,2.78,3.50,2.78,2.650000,3.400000,2.600000,2.73,3.36,2.71,1.83,2.05,1.96,1.94,2.60,3.50,2.70,2.76,3.66,2.78,2.67,3.41,2.68,1.85,2.08,1.81,2.04,1.97,1.97,1.94,1.94,0.00,2024-25,2024,8,5,3,1,0,0,1,NaN,NaN,Everton,Brighton,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,2024-08-17,1,0,H,1,0,H,C Pawson,3,19,1,4,3,12,15,16,2,4,1,0,1.37,5.74,8.10,1.36,5.25,8.00,1.40,3.00,1.98,1.95,1.33,5.50,8.50,1.37,6.00,9.20,1.350000,5.500000,7.750000,1.35,5.70,8.25,1.40,3.09,1.94,1.96,1.35,5.50,8.00,1.37,5.90,8.60,1.35,5.62,8.10,1.42,3.12,1.40,3.01,1.99,1.98,1.93,1.93,-1.50,2024-25,2024,8,5,1,0,0,0,0,NaN,NaN,Newcastle,Southampton,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,2025-03-15,2,4,A,0,3,A,M Salisbury,11,11,4,6,6,3,4,13,1,1,0,0,3.89,3.63,2.03,3.75,3.50,2.00,1.87,2.03,1.88,2.02,3.80,3.60,1.95,4.00,3.70,2.04,2.737992,4.417531,4.333264,3.88,3.64,1.99,1.85,2.04,1.90,2.00,3.75,3.50,2.00,3.93,3.71,2.05,3.80,3.59,1.99,1.92,2.04,1.85,1.99,1.91,2.04,1.87,1.98,0.50,2024-25,2025,3,5,6,1,1,1,1,0.714286,1.571429,Ipswich,Nott'm Forest,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
285,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
287,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
286,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
288,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [18]:
def add_recent_form_features(df, n_matches=5):
    base = df.copy()
    base = base.sort_values('Date')
    home_df = base[['Date', 'HomeTeam', 'FTHG', 'FTAG']].rename(
        columns={'HomeTeam': 'Team', 'FTHG': 'GoalsFor', 'FTAG': 'GoalsAgainst'})
    away_df = base[['Date', 'AwayTeam', 'FTAG', 'FTHG']].rename(
        columns={'AwayTeam': 'Team', 'FTAG': 'GoalsFor', 'FTHG': 'GoalsAgainst'})
    results = pd.concat([home_df, away_df], ignore_index=True)
    results = results.sort_values(['Team', 'Date'])
   
    def get_points(row):
        return 3 if row['GoalsFor'] > row['GoalsAgainst'] else (1 if row['GoalsFor'] == row['GoalsAgainst'] else 0)
    results['Points'] = results.apply(get_points, axis=1)
    results['RollingGF'] = results.groupby('Team')['GoalsFor'].transform(lambda x: x.shift(1).rolling(n_matches, min_periods=1).mean())
    results['RollingGA'] = results.groupby('Team')['GoalsAgainst'].transform(lambda x: x.shift(1).rolling(n_matches, min_periods=1).mean())
    results['RollingPoints'] = results.groupby('Team')['Points'].transform(lambda x: x.shift(1).rolling(n_matches, min_periods=1).sum())
  
    def get_form(row, team_col):
        team = row[team_col]
        date = row['Date']
        row_form = results[(results['Team'] == team) & (results['Date'] < date)].sort_values('Date').tail(1)
        if row_form.empty:
            return pd.Series([np.nan, np.nan, np.nan])
        return row_form[['RollingGF', 'RollingGA', 'RollingPoints']].values[0]
    base[['HomeRecentGF', 'HomeRecentGA', 'HomeRecentPts']] = base.apply(
        lambda row: get_form(row, 'HomeTeam'), axis=1, result_type='expand')
    base[['AwayRecentGF', 'AwayRecentGA', 'AwayRecentPts']] = base.apply(
        lambda row: get_form(row, 'AwayTeam'), axis=1, result_type='expand')
    return base

df = add_recent_form_features(df, n_matches=5)
df = df.dropna(subset=['HomeRecentGF', 'AwayRecentGF'])

In [19]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts
22,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,0.0,1.0,1.0,1.0
20,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,3.0,3.0,0.0,3.0
21,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,3.0,0.0,1.0,0.0
23,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,0.0,0.0,1.0,0.0
25,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,1.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,2025-03-15,1,2,A,0,1,A,R Jones,10,5,3,3,5,1,12,13,0,0,0,0,3.71,3.55,2.11,3.70,3.40,2.00,1.84,2.06,1.83,2.07,3.80,3.50,2.00,3.95,3.65,2.10,2.737992,4.417531,4.333264,3.67,3.56,2.08,1.82,2.07,1.83,2.09,3.70,3.40,2.05,3.85,3.65,2.11,3.63,3.51,2.06,1.86,2.10,1.81,2.03,1.85,2.09,1.80,2.05,0.50,2024-25,2025,3,5,3,1,1,0,1,0.692308,1.428571,Southampton,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.8,3.0,3.0,1.0,1.0,6.0
285,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,6.0,1.6,0.8,10.0
286,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,6.0
287,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,9.0,1.6,0.8,9.0
288,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,3.0,1.2,1.4,7.0

In [20]:
df = df.sort_values('Date')
h2h_home_wins = []
team_stats = {}
home_positions = []
away_positions = []
for idx, row in df.iterrows():
    home = row['HomeTeam']
    away = row['AwayTeam']
    match_date = row['Date']
    prev_matches = df[
        (((df['HomeTeam'] == home) & (df['AwayTeam'] == away)) |
         ((df['HomeTeam'] == away) & (df['AwayTeam'] == home)))
        & (df['Date'] < match_date)
    ].sort_values('Date', ascending=False).head(5)
    home_wins = ((prev_matches['HomeTeam'] == home) & (prev_matches['FTHG'] > prev_matches['FTAG'])).sum()
    h2h_home_wins.append(home_wins)

    league_table = []
    for team, stats in team_stats.items():
        league_table.append({
            'team': team,
            'points': stats['points'],
            'gd': stats['gd'],
            'scored': stats['scored']
        })
    table_df = pd.DataFrame(league_table)
    if not table_df.empty:
        table_df = table_df.sort_values(['points', 'gd', 'scored'], ascending=[False, False, False])
        table_df['position'] = range(1, len(table_df) + 1)
        home_pos = table_df[table_df['team'] == home]['position'].values[0] if home in table_df['team'].values else len(table_df) + 1
        away_pos = table_df[table_df['team'] == away]['position'].values[0] if away in table_df['team'].values else len(table_df) + 1
    else:
        home_pos = away_pos = 1
    home_positions.append(home_pos)
    away_positions.append(away_pos)
  
    home_goals = row['FTHG']
    away_goals = row['FTAG']
    for team in [home, away]:
        if team not in team_stats:
            team_stats[team] = {'points': 0, 'gd': 0, 'scored': 0}
    if home_goals > away_goals:
        team_stats[home]['points'] += 3
    elif home_goals < away_goals:
        team_stats[away]['points'] += 3
    else:
        team_stats[home]['points'] += 1
        team_stats[away]['points'] += 1
    team_stats[home]['gd'] += home_goals - away_goals
    team_stats[away]['gd'] += away_goals - home_goals
    team_stats[home]['scored'] += home_goals
    team_stats[away]['scored'] += away_goals

df['h2h_home_wins_last5'] = h2h_home_wins
df['home_league_position'] = home_positions
df['away_league_position'] = away_positions
df['position_diff'] = df['home_league_position'] - df['away_league_position']

In [21]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts,h2h_home_wins_last5,home_league_position,away_league_position,position_diff
22,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,0.0,1.0,1.0,1.0,0,1,1,0
20,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,3.0,3.0,0.0,3.0,0,3,3,0
21,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,3.0,0.0,1.0,0.0,0,5,5,0
23,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,0.0,0.0,1.0,0.0,0,7,7,0
25,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,1.0,0.0,2.0,0.0,0,9,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,2025-03-15,2,4,A,0,3,A,M Salisbury,11,11,4,6,6,3,4,13,1,1,0,0,3.89,3.63,2.03,3.75,3.50,2.00,1.87,2.03,1.88,2.02,3.80,3.60,1.95,4.00,3.70,2.04,2.737992,4.417531,4.333264,3.88,3.64,1.99,1.85,2.04,1.90,2.00,3.75,3.50,2.00,3.93,3.71,2.05,3.80,3.59,1.99,1.92,2.04,1.85,1.99,1.91,2.04,1.87,1.98,0.50,2024-25,2025,3,5,6,1,1,1,1,0.714286,1.571429,Ipswich,Nott'm Forest,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,1.2,2.8,1.0,2.2,2.2,4.0,0,18,3,15
285,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,6.0,1.6,0.8,10.0,0,6,12,-6
287,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,9.0,1.6,0.8,9.0,0,11,16,-5
286,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,6.0,0,3,4,-1
288,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,3.0,1.2,1.4,7.0,0,19,14,5

In [22]:
N = 5
df['HomePts'] = np.where(df['FTHG'] > df['FTAG'], 3, np.where(df['FTHG'] == df['FTAG'], 1, 0))
df['AwayPts'] = np.where(df['FTAG'] > df['FTHG'], 3, np.where(df['FTAG'] == df['FTHG'], 1, 0))
df['HomeRecentPts'] = (
    df.groupby('HomeTeam')['HomePts'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['AwayRecentPts'] = (
    df.groupby('AwayTeam')['AwayPts'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['HomeGoalDiff'] = df['FTHG'] - df['FTAG']
df['AwayGoalDiff'] = df['FTAG'] - df['FTHG']
df['HomeRecentGoalDiff'] = (
    df.groupby('HomeTeam')['HomeGoalDiff'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['AwayRecentGoalDiff'] = (
    df.groupby('AwayTeam')['AwayGoalDiff'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['RecentGoalDiff'] = df['HomeRecentGoalDiff'] - df['AwayRecentGoalDiff']
df['HomeRecentShotsOnTarget'] = (
    df.groupby('HomeTeam')['HST'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['AwayRecentShotsOnTarget'] = (
    df.groupby('AwayTeam')['AST'].transform(lambda x: x.shift(1).rolling(N, min_periods=1).sum())
)
df['RecentShotsOnTargetDiff'] = df['HomeRecentShotsOnTarget'] - df['AwayRecentShotsOnTarget']
df['PosDiff'] = df['home_league_position'] - df['away_league_position']

for col in ['B365>2.5', 'B365<2.5']:
    median = df[col].median()
    df[f'{col}_missing'] = df[col].isna().astype(int)
    df[col] = df[col].fillna(median)

df['B365>2.5_implied_prob'] = 1 / df['B365>2.5']
df['B365<2.5_implied_prob'] = 1 / df['B365<2.5']
df['OddsMargin'] = df['B365H'] / df['B365A']
df['OU_OddsMargin'] = df['B365>2.5'] / df['B365<2.5']
df['OverUnderRatio'] = df['B365>2.5'] / df['B365<2.5']

df['Weekend'] = df['DayOfWeek'].isin([5, 6]).astype(int)
df['EarlySeason'] = (df['Month'] <= 3).astype(int)

In [23]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts,h2h_home_wins_last5,home_league_position,away_league_position,position_diff,HomePts,AwayPts,HomeGoalDiff,AwayGoalDiff,HomeRecentGoalDiff,AwayRecentGoalDiff,RecentGoalDiff,HomeRecentShotsOnTarget,AwayRecentShotsOnTarget,RecentShotsOnTargetDiff,PosDiff,B365>2.5_missing,B365<2.5_missing,B365>2.5_implied_prob,B365<2.5_implied_prob,OddsMargin,OU_OddsMargin,OverUnderRatio,Weekend,EarlySeason
22,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,NaN,1.0,1.0,NaN,0,1,1,0,0,3,-1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.520833,0.505051,1.078431,0.969697,0.969697,1,0
20,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,NaN,3.0,0.0,NaN,0,3,3,0,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.653595,0.400000,0.156471,0.612000,0.612000,1,0
21,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,NaN,0.0,1.0,NaN,0,5,5,0,3,0,2,-2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.578035,0.476190,0.404157,0.823810,0.823810,1,0
23,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,NaN,0.0,1.0,NaN,0,7,7,0,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.543478,0.485437,1.304348,0.893204,0.893204,1,0
25,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,NaN,0.0,2.0,NaN,0,9,9,0,1,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0.540541,0.487805,0.540541,0.902439,0.902439,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,2025-03-15,2,4,A,0,3,A,M Salisbury,11,11,4,6,6,3,4,13,1,1,0,0,3.89,3.63,2.03,3.75,3.50,2.00,1.87,2.03,1.88,2.02,3.80,3.60,1.95,4.00,3.70,2.04,2.737992,4.417531,4.333264,3.88,3.64,1.99,1.85,2.04,1.90,2.00,3.75,3.50,2.00,3.93,3.71,2.05,3.80,3.59,1.99,1.92,2.04,1.85,1.99,1.91,2.04,1.87,1.98,0.50,2024-25,2025,3,5,6,1,1,1,1,0.714286,1.571429,Ipswich,Nott'm Forest,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,1.2,2.8,3.0,2.2,2.2,6.0,0,18,3,15,0,3,-2,2,-10.0,-2.0,-8.0,24.0,21.0,3.0,15,0,0,0.534759,0.492611,1.875000,0.921182,0.921182,1,1
285,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,7.0,1.6,0.8,13.0,0,6,12,-6,0,3,-1,1,3.0,11.0,-8.0,28.0,31.0,-3.0,-6,0,0,0.694444,0.363636,0.411905,0.523636,0.523636,1,1
287,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,5.0,1.6,0.8,6.0,0,11,16,-5,3,0,2,-2,-2.0,2.0,-4.0,23.0,20.0,3.0,-5,0,0,0.636943,0.420168,0.555556,0.659664,0.659664,1,1
286,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,1.0,0,3,4,-1,3,0,1,-1,5.0,-8.0,13.0,24.0,17.0,7.0,-1,0,0,0.537634,0.520833,0.400000,0.968750,0.968750,1,1
288,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,0.0,1.2,1.4,5.0,0,19,14,5,0,3,-3,3,-12.0,-2.0,-10.0,17.0,18.0,-1.0,5,0,0,0.555556,0.500000,2.459016,0.900000,0.900000,1,1

In [24]:
def rolling_ref_aggression(subdf):
    agg = subdf[['HY', 'AY', 'HR', 'AR']].shift(1).sum(axis=1)
    return agg.rolling(10, min_periods=1).mean()
df = df.sort_values('Date')
df['RefereeAggression'] = (
    df.groupby('Referee').apply(lambda subdf: rolling_ref_aggression(subdf)).reset_index(level=0, drop=True)
)

df = df.replace([np.inf, -np.inf], np.nan)
for col in df.select_dtypes(include=['number']):
    df[col] = df[col].fillna(df[col].median())
for col in df.select_dtypes(include=['object', 'category']):
    df[col] = df[col].fillna(df[col].mode()[0])

df = df.drop_duplicates().reset_index(drop=True)

/var/folders/hh/pmnpfh4502s2v05fp58g729w0000gn/T/ipykernel_96702/1171296694.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Referee').apply(lambda subdf: rolling_ref_aggression(subdf)).reset_index(level=0, drop=True)

In [25]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts,h2h_home_wins_last5,home_league_position,away_league_position,position_diff,HomePts,AwayPts,HomeGoalDiff,AwayGoalDiff,HomeRecentGoalDiff,AwayRecentGoalDiff,RecentGoalDiff,HomeRecentShotsOnTarget,AwayRecentShotsOnTarget,RecentShotsOnTargetDiff,PosDiff,B365>2.5_missing,B365<2.5_missing,B365>2.5_implied_prob,B365<2.5_implied_prob,OddsMargin,OU_OddsMargin,OverUnderRatio,Weekend,EarlySeason,RefereeAggression
0,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,6.0,1.0,1.0,5.0,0,1,1,0,0,3,-1,1,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.520833,0.505051,1.078431,0.969697,0.969697,1,0,0.000000
1,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,6.0,3.0,0.0,5.0,0,3,3,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.653595,0.400000,0.156471,0.612000,0.612000,1,0,0.000000
2,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,6.0,0.0,1.0,5.0,0,5,5,0,3,0,2,-2,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.578035,0.476190,0.404157,0.823810,0.823810,1,0,0.000000
3,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,6.0,0.0,1.0,5.0,0,7,7,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.543478,0.485437,1.304348,0.893204,0.893204,1,0,0.000000
4,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,6.0,0.0,2.0,5.0,0,9,9,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.540541,0.487805,0.540541,0.902439,0.902439,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2025-03-15,1,2,A,0,1,A,R Jones,10,5,3,3,5,1,12,13,0,0,0,0,3.71,3.55,2.11,3.70,3.40,2.00,1.84,2.06,1.83,2.07,3.80,3.50,2.00,3.95,3.65,2.10,2.737992,4.417531,4.333264,3.67,3.56,2.08,1.82,2.07,1.83,2.09,3.70,3.40,2.05,3.85,3.65,2.11,3.63,3.51,2.06,1.86,2.10,1.81,2.03,1.85,2.09,1.80,2.05,0.50,2024-25,2025,3,5,3,1,1,0,1,0.692308,1.428571,Southampton,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.8,3.0,0.0,1.0,1.0,4.0,0,20,17,3,0,3,-1,1,-14.0,-5.0,-9.0,16.0,23.0,-7.0,3,0,0,0.543478,0.485437,1.850000,0.893204,0.893204,1,1,4.600000
265,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,7.0,1.6,0.8,13.0,0,6,12,-6,0,3,-1,1,3.0,11.0,-8.0,28.0,31.0,-3.0,-6,0,0,0.694444,0.363636,0.411905,0.523636,0.523636,1,1,4.200000
266,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,1.0,0,3,4,-1,3,0,1,-1,5.0,-8.0,13.0,24.0,17.0,7.0,-1,0,0,0.537634,0.520833,0.400000,0.968750,0.968750,1,1,4.200000
267,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,5.0,1.6,0.8,6.0,0,11,16,-5,3,0,2,-2,-2.0,2.0,-4.0,23.0,20.0,3.0,-5,0,0,0.636943,0.420168,0.555556,0.659664,0.659664,1,1,3.900000
268,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,0.0,1.2,1.4,5.0,0,19,14,5,0,3,-3,3,-12.0,-2.0,-10.0,17.0,18.0,-1.0,5,0,0,0.555556,0.500000,2.459016,0.900000,0.900000,1,1,2.857143

In [26]:
threshold = 0.95 
df = df.loc[:, df.isnull().mean() < threshold]

In [27]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts,h2h_home_wins_last5,home_league_position,away_league_position,position_diff,HomePts,AwayPts,HomeGoalDiff,AwayGoalDiff,HomeRecentGoalDiff,AwayRecentGoalDiff,RecentGoalDiff,HomeRecentShotsOnTarget,AwayRecentShotsOnTarget,RecentShotsOnTargetDiff,PosDiff,B365>2.5_missing,B365<2.5_missing,B365>2.5_implied_prob,B365<2.5_implied_prob,OddsMargin,OU_OddsMargin,OverUnderRatio,Weekend,EarlySeason,RefereeAggression
0,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,6.0,1.0,1.0,5.0,0,1,1,0,0,3,-1,1,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.520833,0.505051,1.078431,0.969697,0.969697,1,0,0.000000
1,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,6.0,3.0,0.0,5.0,0,3,3,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.653595,0.400000,0.156471,0.612000,0.612000,1,0,0.000000
2,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,6.0,0.0,1.0,5.0,0,5,5,0,3,0,2,-2,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.578035,0.476190,0.404157,0.823810,0.823810,1,0,0.000000
3,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,6.0,0.0,1.0,5.0,0,7,7,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.543478,0.485437,1.304348,0.893204,0.893204,1,0,0.000000
4,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,6.0,0.0,2.0,5.0,0,9,9,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.540541,0.487805,0.540541,0.902439,0.902439,1,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2025-03-15,1,2,A,0,1,A,R Jones,10,5,3,3,5,1,12,13,0,0,0,0,3.71,3.55,2.11,3.70,3.40,2.00,1.84,2.06,1.83,2.07,3.80,3.50,2.00,3.95,3.65,2.10,2.737992,4.417531,4.333264,3.67,3.56,2.08,1.82,2.07,1.83,2.09,3.70,3.40,2.05,3.85,3.65,2.11,3.63,3.51,2.06,1.86,2.10,1.81,2.03,1.85,2.09,1.80,2.05,0.50,2024-25,2025,3,5,3,1,1,0,1,0.692308,1.428571,Southampton,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.8,3.0,0.0,1.0,1.0,4.0,0,20,17,3,0,3,-1,1,-14.0,-5.0,-9.0,16.0,23.0,-7.0,3,0,0,0.543478,0.485437,1.850000,0.893204,0.893204,1,1,4.600000
265,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,7.0,1.6,0.8,13.0,0,6,12,-6,0,3,-1,1,3.0,11.0,-8.0,28.0,31.0,-3.0,-6,0,0,0.694444,0.363636,0.411905,0.523636,0.523636,1,1,4.200000
266,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,1.0,0,3,4,-1,3,0,1,-1,5.0,-8.0,13.0,24.0,17.0,7.0,-1,0,0,0.537634,0.520833,0.400000,0.968750,0.968750,1,1,4.200000
267,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,5.0,1.6,0.8,6.0,0,11,16,-5,3,0,2,-2,-2.0,2.0,-4.0,23.0,20.0,3.0,-5,0,0,0.636943,0.420168,0.555556,0.659664,0.659664,1,1,3.900000
268,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,0.0,1.2,1.4,5.0,0,19,14,5,0,3,-3,3,-12.0,-2.0,-10.0,17.0,18.0,-1.0,5,0,0,0.555556,0.500000,2.459016,0.900000,0.900000,1,1,2.857143

In [28]:
#pd.set_option('display.max_rows', None)
pd.reset_option('display.max_rows')
print("Shape of df:", df.shape)

missing_counts = df.isnull().sum().sort_values(ascending=False)
print("\nMissing values per column:")
print(missing_counts)

missing_perc = (df.isnull().mean() * 100).sort_values(ascending=False)
print("\nPercentage missing per column:")
print(missing_perc)

high_nan_cols = missing_perc[missing_perc > 95].index.tolist()
print("\nColumns with >95% missing values:", high_nan_cols)

print(f"\nTotal columns: {df.shape[1]}")
print(f"Columns with no missing: {(missing_counts==0).sum()}")
print(f"Columns with >50% missing: {(missing_perc > 50).sum()}")

Shape of df: (269, 148)

Missing values per column:
Date                    0
HomeTeam_Southampton    0
HomeTeam_West Ham       0
HomeTeam_Wolves         0
AwayTeam_Arsenal        0
                       ..
MaxH                    0
MaxD                    0
MaxA                    0
AvgH                    0
RefereeAggression       0
Length: 148, dtype: int64

Percentage missing per column:
Date                    0.0
HomeTeam_Southampton    0.0
HomeTeam_West Ham       0.0
HomeTeam_Wolves         0.0
AwayTeam_Arsenal        0.0
                       ...
MaxH                    0.0
MaxD                    0.0
MaxA                    0.0
AvgH                    0.0
RefereeAggression       0.0
Length: 148, dtype: float64

Columns with >95% missing values: []

Total columns: 148
Columns with no missing: 148
Columns with >50% missing: 0

In [29]:
print("All columns in df:")
print(df.columns.tolist())

All columns in df:
['Date', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', '1XBH', '1XBD', '1XBA', 'B365H', 'B365D', 'B365A', 'B365>2.5', 'B365<2.5', 'B365AHH', 'B365AHA', 'BFH', 'BFD', 'BFA', 'BFEH', 'BFED', 'BFEA', 'BWH', 'BWD', 'BWA', 'PSH', 'PSD', 'PSA', 'P>2.5', 'P<2.5', 'PAHH', 'PAHA', 'WHH', 'WHD', 'WHA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'AHh', 'Season', 'Year', 'Month', 'DayOfWeek', 'TotalGoals', 'GoalsOver2_5', 'BTTS', 'Home_2plus', 'Away_2plus', 'HomeTeam_mean_FTHG', 'AwayTeam_mean_FTAG', 'HomeTeam', 'AwayTeam', 'HomeTeam_Arsenal', 'HomeTeam_Aston Villa', 'HomeTeam_Bournemouth', 'HomeTeam_Brentford', 'HomeTeam_Brighton', 'HomeTeam_Chelsea', 'HomeTeam_Crystal Palace', 'HomeTeam_Everton', 'HomeTeam_Fulham', 'HomeTeam_Ipswich', 'HomeTeam_Leicester', 'HomeTeam_Liverpool', 'HomeTeam_Man City', 'HomeTeam_Man United', 'HomeTeam_Newcastle', "HomeTeam_Nott'm Forest", 'HomeTeam_Southampton', 'HomeTeam_Tottenham', 'HomeTeam_West Ham', 'HomeTeam_Wolves', 'AwayTeam_Arsenal', 'AwayTeam_Aston Villa', 'AwayTeam_Bournemouth', 'AwayTeam_Brentford', 'AwayTeam_Brighton', 'AwayTeam_Chelsea', 'AwayTeam_Crystal Palace', 'AwayTeam_Everton', 'AwayTeam_Fulham', 'AwayTeam_Ipswich', 'AwayTeam_Leicester', 'AwayTeam_Liverpool', 'AwayTeam_Man City', 'AwayTeam_Man United', 'AwayTeam_Newcastle', "AwayTeam_Nott'm Forest", 'AwayTeam_Southampton', 'AwayTeam_Tottenham', 'AwayTeam_West Ham', 'AwayTeam_Wolves', 'HomeRecentGF', 'HomeRecentGA', 'HomeRecentPts', 'AwayRecentGF', 'AwayRecentGA', 'AwayRecentPts', 'h2h_home_wins_last5', 'home_league_position', 'away_league_position', 'position_diff', 'HomePts', 'AwayPts', 'HomeGoalDiff', 'AwayGoalDiff', 'HomeRecentGoalDiff', 'AwayRecentGoalDiff', 'RecentGoalDiff', 'HomeRecentShotsOnTarget', 'AwayRecentShotsOnTarget', 'RecentShotsOnTargetDiff', 'PosDiff', 'B365>2.5_missing', 'B365<2.5_missing', 'B365>2.5_implied_prob', 'B365<2.5_implied_prob', 'OddsMargin', 'OU_OddsMargin', 'OverUnderRatio', 'Weekend', 'EarlySeason', 'RefereeAggression']

In [32]:
odds_key = [
    "1XBH", "1XBD", "1XBA", "B365H", "B365D", "B365A", "BFH", "BFD", "BFA", "BFDH", "BFDD", "BFDA", "BMGMH", "BMGMD", "BMGMA",
    "BVH", "BVD", "BVA", "BSH", "BSD", "BSA", "BWH", "BWD", "BWA", "CLH", "CLD", "CLA", "GBH", "GBD", "GBA", "IWH", "IWD", "IWA",
    "LBH", "LBD", "LBA", "PSH", "PSD", "PSA", "PH", "PD", "PA", "SOH", "SOD", "SOA", "SBH", "SBD", "SBA", "SJH", "SJD", "SJA",
    "SYH", "SYD", "SYA", "VCH", "VCD", "VCA", "WHH", "WHD", "WHA", "Bb1X2", "BbMxH", "BbAvH", "BbMxD", "BbAvD", "BbMxA", "BbAvA",
    "MaxH", "MaxD", "MaxA", "AvgH", "AvgD", "AvgA", "BFEH", "BFED", "BFEA",
    "BbOU", "BbMx>2.5", "BbAv>2.5", "BbMx<2.5", "BbAv<2.5", "GB>2.5", "GB<2.5", "B365>2.5", "B365<2.5", "P>2.5", "P<2.5",
    "Max>2.5", "Max<2.5", "Avg>2.5", "Avg<2.5",
    "BbAH", "BbAHh", "AHh", "BbMxAHH", "BbAvAHH", "BbMxAHA", "BbAvAHA", "GBAHH", "GBAHA", "GBAH",
    "LBAHH", "LBAHA", "LBAH", "B365AHH", "B365AHA", "B365AH", "PAHH", "PAHA", "MaxAHH", "MaxAHA", "AvgAHH", "AvgAHA"
]

odds_in_df = [col for col in odds_key if col in df.columns]
print("Betting odds columns present in your DataFrame:")
print(odds_in_df)

odds_missing = [col for col in odds_key if col not in df.columns]
print("\nBetting odds columns missing from your DataFrame:")
print(odds_missing)

Betting odds columns present in your DataFrame:
['1XBH', '1XBD', '1XBA', 'B365H', 'B365D', 'B365A', 'BFH', 'BFD', 'BFA', 'BWH', 'BWD', 'BWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'BFEH', 'BFED', 'BFEA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA']

Betting odds columns missing from your DataFrame:
['BFDH', 'BFDD', 'BFDA', 'BMGMH', 'BMGMD', 'BMGMA', 'BVH', 'BVD', 'BVA', 'BSH', 'BSD', 'BSA', 'CLH', 'CLD', 'CLA', 'GBH', 'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PH', 'PD', 'PA', 'SOH', 'SOD', 'SOA', 'SBH', 'SBD', 'SBA', 'SJH', 'SJD', 'SJA', 'SYH', 'SYD', 'SYA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5', 'GB>2.5', 'GB<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'GBAHH', 'GBAHA', 'GBAH', 'LBAHH', 'LBAHA', 'LBAH', 'B365AH']

In [33]:
df = df.copy()

if 'B365H_prob' not in df.columns:
    df.loc[:, 'B365H_prob'] = 1 / df['B365H']
if 'B365D_prob' not in df.columns:
    df.loc[:, 'B365D_prob'] = 1 / df['B365D']
if 'B365A_prob' not in df.columns:
    df.loc[:, 'B365A_prob'] = 1 / df['B365A']

if not all(col in df.columns for col in ['B365H_prob_norm', 'B365D_prob_norm', 'B365A_prob_norm']):
    prob_sum = df['B365H_prob'] + df['B365D_prob'] + df['B365A_prob']
    df.loc[:, 'B365H_prob_norm'] = df['B365H_prob'] / prob_sum
    df.loc[:, 'B365D_prob_norm'] = df['B365D_prob'] / prob_sum
    df.loc[:, 'B365A_prob_norm'] = df['B365A_prob'] / prob_sum

home_win_cols = ['B365H', 'BSH', 'BWH', 'GBH', 'IWH', 'LBH', 'PSH', 'SOH', 'SBH', 'SJH', 'VCH', 'WHH']
draw_cols = ['B365D', 'BSD', 'BWD', 'GBD', 'IWD', 'LBD', 'PSD', 'SOD', 'SBD', 'SJD', 'VCD', 'WHD']
away_win_cols = ['B365A', 'BSA', 'BWA', 'GBA', 'IWA', 'LBA', 'PSA', 'SOA', 'SBA', 'SJA', 'VCA', 'WHA']

for feat, cols in zip(['cons_mean_home', 'cons_mean_draw', 'cons_mean_away'], [home_win_cols, draw_cols, away_win_cols]):
    if feat not in df.columns:
        df.loc[:, feat] = df[cols].mean(axis=1)

for feat, cols in zip(['cons_min_home', 'cons_min_draw', 'cons_min_away'], [home_win_cols, draw_cols, away_win_cols]):
    if feat not in df.columns:
        df.loc[:, feat] = df[cols].min(axis=1)

for feat, cols in zip(['cons_max_home', 'cons_max_draw', 'cons_max_away'], [home_win_cols, draw_cols, away_win_cols]):
    if feat not in df.columns:
        df.loc[:, feat] = df[cols].max(axis=1)

if 'home_odds_spread' not in df.columns:
    df.loc[:, 'home_odds_spread'] = df['cons_max_home'] - df['cons_min_home']
if 'draw_odds_spread' not in df.columns:
    df.loc[:, 'draw_odds_spread'] = df['cons_max_draw'] - df['cons_min_draw']
if 'away_odds_spread' not in df.columns:
    df.loc[:, 'away_odds_spread'] = df['cons_max_away'] - df['cons_min_away']

if 'B365_overround' not in df.columns:
    df.loc[:, 'B365_overround'] = (1 / df['B365H']) + (1 / df['B365D']) + (1 / df['B365A'])
if 'cons_overround' not in df.columns:
    df.loc[:, 'cons_overround'] = (1 / df['cons_mean_home']) + (1 / df['cons_mean_draw']) + (1 / df['cons_mean_away'])

ou_cols_over = ['BbMx>2.5', 'BbAv>2.5', 'GB>2.5', 'B365>2.5', 'P>2.5', 'Max>2.5', 'Avg>2.5']
ou_cols_under = ['BbMx<2.5', 'BbAv<2.5', 'GB<2.5', 'B365<2.5', 'P<2.5', 'Max<2.5', 'Avg<2.5']

if 'cons_mean_over2.5' not in df.columns:
    df.loc[:, 'cons_mean_over2.5'] = df[ou_cols_over].mean(axis=1)
if 'cons_mean_under2.5' not in df.columns:
    df.loc[:, 'cons_mean_under2.5'] = df[ou_cols_under].mean(axis=1)
if 'cons_over2.5_prob' not in df.columns:
    df.loc[:, 'cons_over2.5_prob'] = 1 / df['cons_mean_over2.5']
if 'cons_under2.5_prob' not in df.columns:
    df.loc[:, 'cons_under2.5_prob'] = 1 / df['cons_mean_under2.5']

ah_home_cols = ['BbMxAHH', 'BbAvAHH', 'GBAHH', 'LBAHH', 'B365AHH', 'PAHH', 'MaxAHH', 'AvgAHH']
ah_away_cols = ['BbMxAHA', 'BbAvAHA', 'GBAHA', 'LBAHA', 'B365AHA', 'PAHA', 'MaxAHA', 'AvgAHA']
if all(col in df.columns for col in ah_home_cols) and 'mean_AH_home' not in df.columns:
    df.loc[:, 'mean_AH_home'] = df[ah_home_cols].mean(axis=1)
if all(col in df.columns for col in ah_away_cols) and 'mean_AH_away' not in df.columns:
    df.loc[:, 'mean_AH_away'] = df[ah_away_cols].mean(axis=1)
if 'AHh' in df.columns and 'market_AHh' not in df.columns:
    df.loc[:, 'market_AHh'] = df['AHh']

if 'target_home_plus_two' not in df.columns and 'FTHG' in df.columns:
    df.loc[:, 'target_home_plus_two'] = (df['FTHG'] >= 2).astype(int)
if 'target_away_plus_two' not in df.columns and 'FTAG' in df.columns:
    df.loc[:, 'target_away_plus_two'] = (df['FTAG'] >= 2).astype(int)

if 'home_away_odds_ratio' not in df.columns:
    df.loc[:, 'home_away_odds_ratio'] = df['cons_mean_home'] / df['cons_mean_away']

KeyError: "['BSH', 'GBH', 'IWH', 'LBH', 'SOH', 'SBH', 'SJH', 'VCH'] not in index"

In [34]:
df

,Date,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,1XBH,1XBD,1XBA,B365H,B365D,B365A,B365>2.5,B365<2.5,B365AHH,B365AHA,BFH,BFD,BFA,BFEH,BFED,BFEA,BWH,BWD,BWA,PSH,PSD,PSA,P>2.5,P<2.5,PAHH,PAHA,WHH,WHD,WHA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,MaxAHH,MaxAHA,AvgAHH,AvgAHA,AHh,Season,Year,Month,DayOfWeek,TotalGoals,GoalsOver2_5,BTTS,Home_2plus,Away_2plus,HomeTeam_mean_FTHG,AwayTeam_mean_FTAG,HomeTeam,AwayTeam,HomeTeam_Arsenal,HomeTeam_Aston Villa,HomeTeam_Bournemouth,HomeTeam_Brentford,HomeTeam_Brighton,HomeTeam_Chelsea,HomeTeam_Crystal Palace,HomeTeam_Everton,HomeTeam_Fulham,HomeTeam_Ipswich,HomeTeam_Leicester,HomeTeam_Liverpool,HomeTeam_Man City,HomeTeam_Man United,HomeTeam_Newcastle,HomeTeam_Nott'm Forest,HomeTeam_Southampton,HomeTeam_Tottenham,HomeTeam_West Ham,HomeTeam_Wolves,AwayTeam_Arsenal,AwayTeam_Aston Villa,AwayTeam_Bournemouth,AwayTeam_Brentford,AwayTeam_Brighton,AwayTeam_Chelsea,AwayTeam_Crystal Palace,AwayTeam_Everton,AwayTeam_Fulham,AwayTeam_Ipswich,AwayTeam_Leicester,AwayTeam_Liverpool,AwayTeam_Man City,AwayTeam_Man United,AwayTeam_Newcastle,AwayTeam_Nott'm Forest,AwayTeam_Southampton,AwayTeam_Tottenham,AwayTeam_West Ham,AwayTeam_Wolves,HomeRecentGF,HomeRecentGA,HomeRecentPts,AwayRecentGF,AwayRecentGA,AwayRecentPts,h2h_home_wins_last5,home_league_position,away_league_position,position_diff,HomePts,AwayPts,HomeGoalDiff,AwayGoalDiff,HomeRecentGoalDiff,AwayRecentGoalDiff,RecentGoalDiff,HomeRecentShotsOnTarget,AwayRecentShotsOnTarget,RecentShotsOnTargetDiff,PosDiff,B365>2.5_missing,B365<2.5_missing,B365>2.5_implied_prob,B365<2.5_implied_prob,OddsMargin,OU_OddsMargin,OverUnderRatio,Weekend,EarlySeason,RefereeAggression,B365H_prob,B365D_prob,B365A_prob,B365H_prob_norm,B365D_prob_norm,B365A_prob_norm
0,2024-08-31,2,3,A,0,0,D,S Attwell,18,17,8,7,8,4,6,1,2,1,0,0,2.83,3.48,2.60,2.75,3.40,2.55,1.92,1.98,2.01,1.89,2.75,3.40,2.60,2.86,3.55,2.68,2.650000,3.400000,2.600000,2.82,3.38,2.62,1.93,1.96,2.03,1.88,2.75,3.40,2.60,2.85,3.50,2.64,2.78,3.40,2.59,1.93,2.00,1.87,1.95,2.03,1.90,2.00,1.87,0.00,2024-25,2024,8,5,5,1,1,1,1,0.000000,1.000000,Everton,Bournemouth,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.0,3.0,6.0,1.0,1.0,5.0,0,1,1,0,0,3,-1,1,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.520833,0.505051,1.078431,0.969697,0.969697,1,0,0.000000,0.363636,0.294118,0.392157,0.346350,0.280136,0.373514
1,2024-08-31,1,1,D,1,0,H,C Kavanagh,11,22,7,4,3,7,12,7,3,2,1,0,1.37,5.84,7.90,1.33,5.50,8.50,1.53,2.50,2.01,1.89,1.33,5.50,8.50,1.36,6.00,9.40,1.360000,5.500000,8.000000,1.34,5.87,8.10,1.54,2.59,2.02,1.89,1.33,5.50,8.50,1.37,6.00,9.00,1.35,5.66,8.11,1.57,2.59,1.53,2.52,2.05,1.92,2.00,1.86,-1.50,2024-25,2024,8,5,2,0,1,0,0,2.000000,3.000000,Arsenal,Brighton,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2.0,0.0,6.0,3.0,0.0,5.0,0,3,3,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.653595,0.400000,0.156471,0.612000,0.612000,1,0,0.000000,0.751880,0.181818,0.117647,0.715160,0.172939,0.111901
2,2024-08-31,3,1,H,1,0,H,J Smith,20,18,7,6,2,8,10,7,2,1,0,0,1.79,4.12,4.47,1.75,3.90,4.33,1.73,2.10,2.01,1.89,1.75,3.90,4.60,1.82,4.10,4.80,1.750000,3.900000,4.400000,1.79,3.90,4.51,1.74,2.18,2.00,1.90,1.75,3.90,4.60,1.82,4.12,4.70,1.77,3.97,4.46,1.76,2.21,1.73,2.15,2.04,1.92,1.97,1.89,-0.75,2024-25,2024,8,5,4,1,1,1,0,2.000000,0.000000,Brentford,Southampton,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,2.0,1.0,6.0,0.0,1.0,5.0,0,5,5,0,3,0,2,-2,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.578035,0.476190,0.404157,0.823810,0.823810,1,0,0.000000,0.571429,0.256410,0.230947,0.539702,0.242174,0.218124
3,2024-08-31,1,1,D,1,1,D,L Smith,11,9,4,4,8,6,15,15,2,3,0,0,3.13,3.66,2.31,3.00,3.50,2.30,1.84,2.06,1.87,2.03,3.10,3.40,2.30,3.20,3.60,2.42,3.100000,3.500000,2.250000,3.14,3.53,2.32,1.83,2.06,1.89,2.01,3.10,3.50,2.30,3.20,3.66,2.38,3.10,3.50,2.31,1.88,2.07,1.82,2.03,1.91,2.08,1.86,1.98,0.25,2024-25,2024,8,5,2,0,1,0,0,0.000000,0.000000,Ipswich,Fulham,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0.0,2.0,6.0,0.0,1.0,5.0,0,7,7,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.543478,0.485437,1.304348,0.893204,0.893204,1,0,0.000000,0.333333,0.285714,0.434783,0.316306,0.271120,0.412574
4,2024-08-31,1,1,D,1,1,D,S Hooper,16,11,5,3,7,3,15,18,3,4,0,0,2.04,3.76,3.70,2.00,3.70,3.70,1.85,2.05,2.03,1.87,2.00,3.60,3.75,2.08,3.80,3.85,2.100000,3.600000,3.500000,2.02,3.70,3.71,1.85,2.04,2.03,1.88,2.05,3.60,3.60,2.10,3.76,3.79,2.03,3.66,3.65,1.86,2.09,1.83,2.02,2.08,1.88,2.02,1.85,-0.50,2024-25,2024,8,5,2,0,1,0,0,1.000000,0.000000,Nott'm Forest,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,1.0,1.0,6.0,0.0,2.0,5.0,0,9,9,0,1,1,0,0,0.0,-1.0,0.0,22.0,18.0,3.0,0,0,0,0.540541,0.487805,0.540541,0.902439,0.902439,1,0,0.000000,0.500000,0.270270,0.270270,0.480519,0.259740,0.259740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,2025-03-15,1,2,A,0,1,A,R Jones,10,5,3,3,5,1,12,13,0,0,0,0,3.71,3.55,2.11,3.70,3.40,2.00,1.84,2.06,1.83,2.07,3.80,3.50,2.00,3.95,3.65,2.10,2.737992,4.417531,4.333264,3.67,3.56,2.08,1.82,2.07,1.83,2.09,3.70,3.40,2.05,3.85,3.65,2.11,3.63,3.51,2.06,1.86,2.10,1.81,2.03,1.85,2.09,1.80,2.05,0.50,2024-25,2025,3,5,3,1,1,0,1,0.692308,1.428571,Southampton,Wolves,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,0.8,3.0,0.0,1.0,1.0,4.0,0,20,17,3,0,3,-1,1,-14.0,-5.0,-9.0,16.0,23.0,-7.0,3,0,0,0.543478,0.485437,1.850000,0.893204,0.893204,1,1,4.600000,0.270270,0.294118,0.500000,0.253921,0.276326,0.469754
265,2025-03-15,1,2,A,1,1,D,C Pawson,17,10,5,4,4,3,13,7,3,0,0,0,1.78,4.23,4.38,1.73,4.20,4.20,1.44,2.75,1.95,1.95,1.75,4.10,4.40,1.80,4.30,4.50,2.737992,4.417531,4.333264,1.77,4.21,4.29,1.50,2.67,1.98,1.93,1.75,4.00,4.20,1.80,4.30,4.40,1.76,4.16,4.25,1.51,2.80,1.48,2.66,1.98,1.96,1.94,1.90,-0.75,2024-25,2025,3,5,3,1,1,0,1,1.307692,1.384615,Bournemouth,Brentford,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.8,1.2,7.0,1.6,0.8,13.0,0,6,12,-6,0,3,-1,1,3.0,11.0,-8.0,28.0,31.0,-3.0,-6,0,0,0.694444,0.363636,0.411905,0.523636,0.523636,1,1,4.200000,0.578035,0.238095,0.238095,0.548303,0.225849,0.225849
266,2025-03-16,1,0,H,1,0,H,C Kavanagh,12,8,4,2,5,4,10,13,3,3,0,0,1.82,3.91,4.53,1.80,3.60,4.50,1.86,1.92,2.06,1.84,1.80,3.75,4.50,1.86,3.90,4.80,2.737992,4.417531,4.333264,1.81,3.78,4.55,1.92,1.97,2.07,1.85,1.80,3.70,4.33,1.85,3.91,4.60,1.81,3.74,4.44,1.93,1.98,1.88,1.94,2.08,1.85,2.03,1.81,-0.75,2024-25,2025,3,6,1,0,0,0,0,2.076923,1.857143,Arsenal,Chelsea,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,1.6,0.4,10.0,1.6,1.8,1.0,0,3,4,-1,3,0,1,-1,5.0,-8.0,13.0,24.0,17.0,7.0,-1,0,0,0.537634,0.520833,0.400000,0.968750,0.968750,1,1,4.200000,0.555556,0.277778,0.222222,0.526316,0.263158,0.210526
267,2025-03-16,2,0,H,0,0,D,A Madley,13,12,4,4,6,5,13,10,0,0,0,0,2.03,4.04,3.51,2.00,3.75,3.60,1.57,2.38,2.03,1.87,2.00,3.80,3.60,2.08,3.95,3.70,2.737992,4.417531,4.333264,2.03,3.88,3.53,1.60,2.42,2.03,1.88,1.95,3.90,3.40,2.10,4.04,3.65,2.01,3.84,3.48,1.61,2.50,1.57,2.42,2.04,1.90,2.00,1.85,-0.50,2024-25,2025,3,6,2,0,0,1,0,1.428571,1.923077,Fulham,Tottenham,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,1.2,1.2,5.0,1.6,0.8,6.0,0,11,16,-5,3,0,2,-2,-2.0,2.0,-4.0,23.0,20.0,3.0,-5,0,0,0.636943,0.420168,0.555556,0.659664,0.659664,1,1,3.900000,0.500000,0.266667,0.277778,0.478723,0.255319,0.265957
268,2025-03-16,0,3,A,0,1,A,T Bramall,11,18,3,5,6,4,6,6,2,0,0,0,4.28,3.91,1.87,4.50,3.50,1.83,1.80,2.00,2.05,1.85,4.33,3.70,1.85,4.60,3.85,1.88,2.737992,4.417531,4.333264,4.21,3.86,1.85,1.81,2.07,2.05,1.86,4.00,3.75,1.85,4.50,3.91,1.87,4.21,3.76,1.84,1.85,2.10,1.79,2.04,2.08,1.86,2.02,1.83,0.50,2024-25,2025,3,6,3,1,0,0,1,0.785714,1.000000,Leicester,Man United,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,0.4,2.6,0.0,1.2,1.4,5.0,0,19,14,5,0,3,-3,3,-12.0,-2.0,-10.0,17.0,18.0,-1.0,5,0,0,0.555556,0.500000,2.459016,0.900000,0.900000,1,1,2.857143,0.222222,0.285714,0.546448,0.210760,0.270977,0.518263

In [34]:
#pd.set_option('display.max_rows', None)
pd.reset_option('display.max_rows')
print("Shape of df:", df.shape)

missing_counts = df.isnull().sum().sort_values(ascending=False)
print("\nMissing values per column:")
print(missing_counts)

missing_perc = (df.isnull().mean() * 100).sort_values(ascending=False)
print("\nPercentage missing per column:")
print(missing_perc)

high_nan_cols = missing_perc[missing_perc > 95].index.tolist()
print("\nColumns with >95% missing values:", high_nan_cols)

print(f"\nTotal columns: {df.shape[1]}")
print(f"Columns with no missing: {(missing_counts==0).sum()}")
print(f"Columns with >50% missing: {(missing_perc > 50).sum()}")

Shape of df: (7901, 266)

Missing values per column:
Date                    0
AwayTeam_Leicester      0
AwayTeam_Bournemouth    0
AwayTeam_Brentford      0
AwayTeam_Brighton       0
                       ..
AvgH                    0
AvgD                    0
AvgA                    0
Max>2.5                 0
home_away_odds_ratio    0
Length: 266, dtype: int64

Percentage missing per column:
Date                    0.0
AwayTeam_Leicester      0.0
AwayTeam_Bournemouth    0.0
AwayTeam_Brentford      0.0
AwayTeam_Brighton       0.0
                       ...
AvgH                    0.0
AvgD                    0.0
AvgA                    0.0
Max>2.5                 0.0
home_away_odds_ratio    0.0
Length: 266, dtype: float64

Columns with >95% missing values: []

Total columns: 266
Columns with no missing: 266
Columns with >50% missing: 0

In [35]:
df.to_csv("../../data/processed/engineered_betting_features.csv", index=False)

In [36]:
df.columns.tolist()

['Date',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HC',
 'AC',
 'HF',
 'AF',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'B365>2.5',
 'B365<2.5',
 'B365AHH',
 'B365AHA',
 'B365AH',
 'VCH',
 'VCD',
 'VCA',
 'BSH',
 'BSD',
 'BSA',
 'BWH',
 'BWD',
 'BWA',
 'GBH',
 'GBD',
 'GBA',
 'GB>2.5',
 'GB<2.5',
 'GBAHH',
 'GBAHA',
 'GBAH',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'LBAHH',
 'LBAHA',
 'LBAH',
 'PSH',
 'PSD',
 'PSA',
 'P>2.5',
 'P<2.5',
 'PAHH',
 'PAHA',
 'SOH',
 'SOD',
 'SOA',
 'SBH',
 'SBD',
 'SBA',
 'SJH',
 'SJD',
 'SJA',
 'WHH',
 'WHD',
 'WHA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'AHh',
 'Season',
 'Year',
 'Month',
 'DayOfWeek',
 'TotalGoals',
 'GoalsOver2_5',
 'BTTS',
 'Home_2plus',
 'Away_2plus',
 'HomeTeam_mean_FTHG',
 'AwayTeam_mean_FTAG',
 'HomeTeam',
 'AwayTeam',
 'HomeTeam_Arsenal',
 'HomeTeam_Aston Villa',
 'HomeTeam_Birmingham',
 'HomeTeam_Blackburn',
 'HomeTeam_Blackpool',
 'HomeTeam_Bolton',
 'HomeTeam_Bournemouth',
 'HomeTeam_Brentford',
 'HomeTeam_Brighton',
 'HomeTeam_Burnley',
 'HomeTeam_Cardiff',
 'HomeTeam_Charlton',
 'HomeTeam_Chelsea',
 'HomeTeam_Crystal Palace',
 'HomeTeam_Derby',
 'HomeTeam_Everton',
 'HomeTeam_Fulham',
 'HomeTeam_Huddersfield',
 'HomeTeam_Hull',
 'HomeTeam_Leeds',
 'HomeTeam_Leicester',
 'HomeTeam_Liverpool',
 'HomeTeam_Luton',
 'HomeTeam_Man City',
 'HomeTeam_Man United',
 'HomeTeam_Middlesbrough',
 'HomeTeam_Newcastle',
 'HomeTeam_Norwich',
 "HomeTeam_Nott'm Forest",
 'HomeTeam_Portsmouth',
 'HomeTeam_QPR',
 'HomeTeam_Reading',
 'HomeTeam_Sheffield United',
 'HomeTeam_Southampton',
 'HomeTeam_Stoke',
 'HomeTeam_Sunderland',
 'HomeTeam_Swansea',
 'HomeTeam_Tottenham',
 'HomeTeam_Watford',
 'HomeTeam_West Brom',
 'HomeTeam_West Ham',
 'HomeTeam_Wigan',
 'HomeTeam_Wolves',
 'AwayTeam_Arsenal',
 'AwayTeam_Aston Villa',
 'AwayTeam_Birmingham',
 'AwayTeam_Blackburn',
 'AwayTeam_Blackpool',
 'AwayTeam_Bolton',
 'AwayTeam_Bournemouth',
 'AwayTeam_Brentford',
 'AwayTeam_Brighton',
 'AwayTeam_Burnley',
 'AwayTeam_Cardiff',
 'AwayTeam_Charlton',
 'AwayTeam_Chelsea',
 'AwayTeam_Crystal Palace',
 'AwayTeam_Derby',
 'AwayTeam_Everton',
 'AwayTeam_Fulham',
 'AwayTeam_Huddersfield',
 'AwayTeam_Hull',
 'AwayTeam_Leeds',
 'AwayTeam_Leicester',
 'AwayTeam_Liverpool',
 'AwayTeam_Luton',
 'AwayTeam_Man City',
 'AwayTeam_Man United',
 'AwayTeam_Middlesbrough',
 'AwayTeam_Newcastle',
 'AwayTeam_Norwich',
 "AwayTeam_Nott'm Forest",
 'AwayTeam_Portsmouth',
 'AwayTeam_QPR',
 'AwayTeam_Reading',
 'AwayTeam_Sheffield United',
 'AwayTeam_Southampton',
 'AwayTeam_Stoke',
 'AwayTeam_Sunderland',
 'AwayTeam_Swansea',
 'AwayTeam_Tottenham',
 'AwayTeam_Watford',
 'AwayTeam_West Brom',
 'AwayTeam_West Ham',
 'AwayTeam_Wigan',
 'AwayTeam_Wolves',
 'HomeRecentGF',
 'HomeRecentGA',
 'HomeRecentPts',
 'AwayRecentGF',
 'AwayRecentGA',
 'AwayRecentPts',
 'h2h_home_wins_last5',
 'home_league_position',
 'away_league_position',
 'position_diff',
 'HomePts',
 'AwayPts',
 'HomeGoalDiff',
 'AwayGoalDiff',
 'HomeRecentGoalDiff',
 'AwayRecentGoalDiff',
 'RecentGoalDiff',
 'HomeRecentShotsOnTarget',
 'AwayRecentShotsOnTarget',
 'RecentShotsOnTargetDiff',
 'PosDiff',
 'B365>2.5_missing',
 'B365<2.5_missing',
 'B365>2.5_implied_prob',
 'B365<2.5_implied_prob',
 'OddsMargin',
 'OU_OddsMargin',
 'OverUnderRatio',
 'Weekend',
 'EarlySeason',
 'RefereeAggression',
 'B365H_prob',
 'B365D_prob',
 'B365A_prob',
 'B365H_prob_norm',
 'B365D_prob_norm',
 'B365A_prob_norm',
 'cons_mean_home',
 'cons_mean_draw',
 'cons_mean_away',
 'cons_min_home',
 'cons_min_draw',
 'cons_min_away',
 'cons_max_home',
 'cons_max_draw',
 'cons_max_away',
 'home_odds_spread',
 'draw_odds_spread',
 'away_odds_spread',
 'B365_overround',
 'cons_overround',
 'cons_mean_over2.5',
 'cons_mean_under2.5',
 'cons_over2.5_prob',
 'cons_under2.5_prob',
 'mean_AH_home',
 'mean_AH_away',
 'market_AHh',
 'target_home_plus_two',
 'target_away_plus_two',
 'home_away_odds_ratio']